project:
  type: website

website:
  title: "Let's Innovate and Create"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nsal0017
format:
  html:
    theme: Flaty
    css: styles.css



